import Game.Metadata
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Tactic.Common

World "GroupsAndOrders"
Level 3

Title "Order Divides the Group Size"

Introduction
"
## A Genuinely Deep Fact

Here is a theorem that is *not* obvious from the definition of order alone:
in a finite group `G`, the order of every single element `g` evenly
**divides** the size of the whole group, `Fintype.card G`. This is a
consequence of Lagrange's Theorem (the cosets of the subgroup generated by
`g` partition `G` into equal-sized pieces).

### Your Task

Prove that `orderOf g` divides `Fintype.card G`.

### Strategy

Mathlib already has this exact consequence of Lagrange's Theorem available
directly.
"

Statement {G : Type} [Group G] [Fintype G] (g : G) :
    orderOf g ∣ Fintype.card G := by
  Hint "This is a direct consequence of Lagrange's Theorem, already in Mathlib. Type: exact orderOf_dvd_card"
  exact orderOf_dvd_card

Conclusion
"
Every element's order divides the group's size — so in a group of *prime*
order `p`, every non-identity element's order must be `p` itself (the only
divisors of a prime are `1` and itself, and order `1` means the identity).
That's exactly why cryptographic protocols deliberately choose groups of
prime order: it rules out an attacker restricting their search to some
small subgroup.

**APOS stage:** Object — a structural theorem about the group as a whole,
not just a single element's behavior.
"

NewTheorem orderOf_dvd_card
